export const CART_REDUCER_ACTIONS = {
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  TOGGLE_AMOUNT: 'TOGGLE_AMOUNT',
  CLEAR_CART: 'CLEAR_CART',
  GET_TOTALS: 'GET_TOTALS',
};
